### ISSUE TITLE
Changing table prefix does not work on case-sensitive filesystems.

### ISSUE THREAD

**Issue by TH3L0N3W0LF** [XereoNet/SpaceBukkit#10]
I attempted to change the table prefix, but I got these errors:

Warning (2): file(/var/www/admin/SpaceBukkit/app/config/database.php): failed to open stream: No such file or directory [APP/Controller/TsettingsController.php, line 490]

Warning (2): implode() [http://php.net/function.implode]: Argument must be an array [APP/Controller/TsettingsController.php, line 490]

Warning (2): fopen(/var/www/admin/SpaceBukkit/app/config/database.php) [http://php.net/function.fopen]: failed to open stream: No such file or directory [APP/Controller/TsettingsController.php, line 492]

Warning (2): fwrite() expects parameter 1 to be resource, boolean given [APP/Controller/TsettingsController.php, line 498]

The database file exists, but config is capitalized. Manually changing the path in TsettingsController to Config instead of config fixes the issue, so it's a problem with case-sensitive filesystems.

**Comment by Antariano** [comment]
I'm on it!

**Comment by Antariano** [comment]
Fixed
