### ISSUE TITLE
Errors at the dashboard

### ISSUE THREAD

**Issue by ghost** [XereoNet/SpaceBukkit#103]
I got suddendly these errors when I connected to the SpaceBukkit.

Warning (2): simplexml_load_file(): http://spacebukkit.xereo.net/build/message.xml:11: parser error : expected '>' [APP/Controller/AppController.php, line 172]

Warning (2): simplexml_load_file() [http://php.net/function.simplexml-load-file]:    [APP/Controller/AppController.php, line 172]

Warning (2): simplexml_load_file() [http://php.net/function.simplexml-load-file]:            ^ [APP/Controller/AppController.php, line 172]

Warning (2): simplexml_load_file() [http://php.net/function.simplexml-load-file]: http://spacebukkit.xereo.net/build/message.xml:12: parser error : Opening and ending tag mismatch: MESSAGES line 6 and SPACEBUKKIT [APP/Controller/AppController.php, line 172]

Warning (2): simplexml_load_file() [http://php.net/function.simplexml-load-file]:  [APP/Controller/AppController.php, line 172]

Warning (2): simplexml_load_file() [http://php.net/function.simplexml-load-file]:               ^ [APP/Controller/AppController.php, line 172]

Warning (2): simplexml_load_file() [http://php.net/function.simplexml-load-file]: http://spacebukkit.xereo.net/build/message.xml:13: parser error : Premature end of data in tag SPACEBUKKIT line 1 [APP/Controller/AppController.php, line 172]

Warning (2): simplexml_load_file() [http://php.net/function.simplexml-load-file]:  [APP/Controller/AppController.php, line 172]

Warning (2): simplexml_load_file() [http://php.net/function.simplexml-load-file]: ^ [APP/Controller/AppController.php, line 172]

Warning (2): simplexml_load_file(http://ci.bukkit.org/other/latest_recommended.rss) [http://php.net/function.simplexml-load-file]: failed to open stream: HTTP request failed! HTTP/1.1 404 Not Found
 [APP/Controller/DashController.php, line 135]

Warning (2): simplexml_load_file() [http://php.net/function.simplexml-load-file]: I/O warning : failed to load external entity "http://ci.bukkit.org/other/latest_recommended.rss" [APP/Controller/DashController.php, line 135]

Notice (8): Trying to get property of non-object [APP/Controller/DashController.php, line 136]

Notice (8): Trying to get property of non-object [APP/Controller/DashController.php, line 136]

Notice (8): Trying to get property of non-object [APP/Controller/DashController.php, line 136]

**Comment by Antariano** [comment]
Install 1.07 please
