### ISSUE TITLE
Location /sb/install not found

### ISSUE THREAD

**Issue by davidcole1340** [XereoNet/SpaceBukkit#107]
Everytime I try to go and install SpaceCP, I get an error saying "The directory /sb/install could not be found."
Link: http://mc2.dalemcrft.co.cc/sb/

**Comment by CromAr** [comment]
You must have mod_rewrite enabled on your Apache :)

**Comment by davidcole1340** [comment]
I do

**Comment by Antariano** [comment]
Should be fixed
