### ISSUE TITLE
SpaceCP borked after pressing on plugins

### ISSUE THREAD

**Issue by maniacmusic** [XereoNet/SpaceBukkit#108]
When clicking on the plugins tab, the SpaceCP crashes.

It's loading forever, fix: restarting the webserver (/etc/init.d/apache2 restart)

**Comment by hlfbt** [comment]
Log: http://pastebin.com/A3escFcx

**Comment by maniacmusic** [comment]
fixed in SB #23
http://dev.drdanick.com/jenkins/job/SpaceBukkit/23/
