### ISSUE TITLE
Notice 8

### ISSUE THREAD

**Issue by iceraven721** [XereoNet/SpaceBukkit#112]
Whenever I try to make a user with anything other than owner or superuser, and when that user tries to log in, they get:

Notice (8): Undefined index: Server [APP\Controller\AppController.php, line 336]
Code Context

AppController::beforeFilter() - APP\Controller\AppController.php, line 336
UsersController::beforeFilter() - APP\Controller\UsersController.php, line 48
Controller::startupProcess() - CORE\Cake\Controller\Controller.php, line 605
Dispatcher::_invoke() - CORE\Cake\Routing\Dispatcher.php, line 104
Dispatcher::dispatch() - CORE\Cake\Routing\Dispatcher.php, line 89
[main] - APP\webroot\index.php, line 96

**Comment by Antariano** [comment]
Seems to be an issue with sessions, does refreshing the page help?

**Comment by GTB3NW** [comment]
Nope, clearing cache and cookies does not either. The users which receive the errors are ones which have servers selected for them (None super-users)

**Comment by Antariano** [comment]
ok, please provide more information about the user.
Is he added to a server?
With what permissions?
Thanks for your help!

**Comment by iceraven721** [comment]
This happens when creating any user below owner.  The first time a user logs in, they see this "Notice 8" error in the navigation bar.  It will repeat for however many buttons they are supposed to see.  Then when they refresh, this goes away.

**Comment by Antariano** [comment]
Ok, found the error, fixed :)
