### ISSUE TITLE
Panel display errors

### ISSUE THREAD

**Issue by GTB3NW** [XereoNet/SpaceBukkit#115]
One of our moderators with the role settings: 
- Dash
- User

Is getting the following page sent to him from spacebukkit: http://pastebin.com/JV40WqKC (Pastie would not accept the content due to it being over 64KB)

There was an error on login which displays the notice(8) spam, but after reload that disappears and errors only display when hovering over the server list.

Thanks

**Comment by iceraven721** [comment]
Yup, I just recently posted that one.  Having the same problem.

**Comment by Antariano** [comment]
https://github.com/SpaceDev/SpaceBukkit/issues/112
Duplicate
