### ISSUE TITLE
Add new User -> Favourite Server Error

### ISSUE THREAD

**Issue by lucasdidur** [XereoNet/SpaceBukkit#116]
Show this error on <selected></selected>

```
        Notice (8): Undefined variable: edituser [APP/View/Users/add.ctp, line 69]Code Context            <?php



        if ($edituser["User"]["is_super"] == 1){
```

$___viewFn  =   "/home/ehaqui/public_html/mc/painel/app/View/Users/add.ctp"
$___dataForView =   array(
    "gototab" => null,
    "current_theme" => "Spacebukkit",
    "languages" => array(
    "English" => "eng",
    "Finnish" => "fin",
    "German" => "ger",
    "Polish" => "pol",
    "French" => "fre"
),
    "themes" => array(
    "./themes/Spacebukkit" => array(),
    "./themes/Fusion green" => array(),
    "./themes/Fusion Blue" => array(),
    "./themes/Fusion Purple" => array()
),
    "is_super" => "1",
    "current_user_id" => "1",
    "username" => "super"
)
$gototab    =   null
$current_theme  =   "Spacebukkit"
$languages  =   array(
    "English" => "eng",
    "Finnish" => "fin",
    "German" => "ger",
    "Polish" => "pol",
    "French" => "fre"
)
$themes =   array(
    "./themes/Spacebukkit" => array(
    "level" => 1,
    "dir" => 1,
    "name" => "Spacebukkit",
    "path" => "./themes/"
),
    "./themes/Fusion green" => array(
    "level" => 1,
    "dir" => 1,
    "name" => "Fusion green",
    "path" => "./themes/"
),
    "./themes/Fusion Blue" => array(
    "level" => 1,
    "dir" => 1,
    "name" => "Fusion Blue",
    "path" => "./themes/"
),
    "./themes/Fusion Purple" => array(
    "level" => 1,
    "dir" => 1,
    "name" => "Fusion Purple",
    "path" => "./themes/"
)
)
$is_super   =   "1"
$current_user_id    =   "1"
$username   =   "super"
$theme  =   array(
    "level" => 1,
    "dir" => 1,
    "name" => "Fusion Purple",
    "path" => "./themes/"
)include - APP/View/Users/add.ctp, line 69
View::_render() - CORE/Cake/View/View.php, line 598
View::render() - CORE/Cake/View/View.php, line 365
Controller::render() - CORE/Cake/Controller/Controller.php, line 900
Dispatcher::_invoke() - CORE/Cake/Routing/Dispatcher.php, line 114
Dispatcher::dispatch() - CORE/Cake/Routing/Dispatcher.php, line 89
[main] - APP/webroot/index.php, line 96Notice (8): Undefined variable: all_servers [APP/View/Users/add.ctp, line 85]Code Context            } else {

```
            foreach ($all_servers as $server) {
```

$___viewFn  =   "/home/ehaqui/public_html/mc/painel/app/View/Users/add.ctp"
$___dataForView =   array(
    "gototab" => null,
    "current_theme" => "Spacebukkit",
    "languages" => array(
    "English" => "eng",
    "Finnish" => "fin",
    "German" => "ger",
    "Polish" => "pol",
    "French" => "fre"
),
    "themes" => array(
    "./themes/Spacebukkit" => array(),
    "./themes/Fusion green" => array(),
    "./themes/Fusion Blue" => array(),
    "./themes/Fusion Purple" => array()
),
    "is_super" => "1",
    "current_user_id" => "1",
    "username" => "super"
)
$gototab    =   null
$current_theme  =   "Spacebukkit"
$languages  =   array(
    "English" => "eng",
    "Finnish" => "fin",
    "German" => "ger",
    "Polish" => "pol",
    "French" => "fre"
)
$themes =   array(
    "./themes/Spacebukkit" => array(
    "level" => 1,
    "dir" => 1,
    "name" => "Spacebukkit",
    "path" => "./themes/"
),
    "./themes/Fusion green" => array(
    "level" => 1,
    "dir" => 1,
    "name" => "Fusion green",
    "path" => "./themes/"
),
    "./themes/Fusion Blue" => array(
    "level" => 1,
    "dir" => 1,
    "name" => "Fusion Blue",
    "path" => "./themes/"
),
    "./themes/Fusion Purple" => array(
    "level" => 1,
    "dir" => 1,
    "name" => "Fusion Purple",
    "path" => "./themes/"
)
)
$is_super   =   "1"
$current_user_id    =   "1"
$username   =   "super"
$theme  =   array(
    "level" => 1,
    "dir" => 1,
    "name" => "Fusion Purple",
    "path" => "./themes/"
)include - APP/View/Users/add.ctp, line 85
View::_render() - CORE/Cake/View/View.php, line 598
View::render() - CORE/Cake/View/View.php, line 365
Controller::render() - CORE/Cake/Controller/Controller.php, line 900
Dispatcher::_invoke() - CORE/Cake/Routing/Dispatcher.php, line 114
Dispatcher::dispatch() - CORE/Cake/Routing/Dispatcher.php, line 89
[main] - APP/webroot/index.php, line 96Warning (2): Invalid argument supplied for foreach() [APP/View/Users/add.ctp, line 85]Code Context            } else {

```
            foreach ($all_servers as $server) {
```

$___viewFn  =   "/home/ehaqui/public_html/mc/painel/app/View/Users/add.ctp"
$___dataForView =   array(
    "gototab" => null,
    "current_theme" => "Spacebukkit",
    "languages" => array(
    "English" => "eng",
    "Finnish" => "fin",
    "German" => "ger",
    "Polish" => "pol",
    "French" => "fre"
),
    "themes" => array(
    "./themes/Spacebukkit" => array(),
    "./themes/Fusion green" => array(),
    "./themes/Fusion Blue" => array(),
    "./themes/Fusion Purple" => array()
),
    "is_super" => "1",
    "current_user_id" => "1",
    "username" => "super"
)
$gototab    =   null
$current_theme  =   "Spacebukkit"
$languages  =   array(
    "English" => "eng",
    "Finnish" => "fin",
    "German" => "ger",
    "Polish" => "pol",
    "French" => "fre"
)
$themes =   array(
    "./themes/Spacebukkit" => array(
    "level" => 1,
    "dir" => 1,
    "name" => "Spacebukkit",
    "path" => "./themes/"
),
    "./themes/Fusion green" => array(
    "level" => 1,
    "dir" => 1,
    "name" => "Fusion green",
    "path" => "./themes/"
),
    "./themes/Fusion Blue" => array(
    "level" => 1,
    "dir" => 1,
    "name" => "Fusion Blue",
    "path" => "./themes/"
),
    "./themes/Fusion Purple" => array(
    "level" => 1,
    "dir" => 1,
    "name" => "Fusion Purple",
    "path" => "./themes/"
)
)
$is_super   =   "1"
$current_user_id    =   "1"
$username   =   "super"
$theme  =   array(
    "level" => 1,
    "dir" => 1,
    "name" => "Fusion Purple",
    "path" => "./themes/"
)include - APP/View/Users/add.ctp, line 85
View::_render() - CORE/Cake/View/View.php, line 598
View::render() - CORE/Cake/View/View.php, line 365
Controller::render() - CORE/Cake/Controller/Controller.php, line 900
Dispatcher::_invoke() - CORE/Cake/Routing/Dispatcher.php, line 114
Dispatcher::dispatch() - CORE/Cake/Routing/Dispatcher.php, line 89
[main] - APP/webroot/index.php, line 96

**Comment by Antariano** [comment]
I can't seem to be able to replicate this. Closed for now, will be re-opened if 1.1 doesn't fix the issue.
