### ISSUE TITLE
Restart gives errors

### ISSUE THREAD

**Issue by Lolmewn** [XereoNet/SpaceBukkit#12]
In the web control panel: Warning (2): in_array() expects parameter 2 to be array, null given [APP\Controller\DashController.php, line 176]
In the server side: Something with json, but it seems the log gets wiped at a restart so I can't track it easily..

**Comment by Antariano** [comment]
I'm on it.

**Comment by Antariano** [comment]
I think I fixed it, we'll see with 1.02, in case it wasn't fixed we'll reopen the issue
