### ISSUE TITLE
Can't delete scheduled job

### ISSUE THREAD

**Issue by ray73864** [XereoNet/SpaceBukkit#121]
We have a scheduled job on our game that we can't seem to delete. The jobs.yml file shows it as being gone, but the 'schedule' tab shows it as still being there and the command that it runs 'it says a message in-game' still gets shown every couple of minutes.

We have shut down the server, etc... to no avail.

**Comment by NeatMonster** [comment]
Please update SpaceBukkit and SpaceRTK to build #27 (ignore the 'Do not use builds below!' message).

http://dev.drdanick.com/jenkins/

**Comment by ray73864** [comment]
where does the SpaceRTK file get put?

**Comment by NeatMonster** [comment]
/toolkit/modules/ directory.

**Comment by ray73864** [comment]
do i need to restart the server or just reload it?

**Comment by NeatMonster** [comment]
Restart, but now only the server: RemoteToolkit must be restarted too.

**Comment by ray73864** [comment]
done. the message is gone.

when i start the server up, i do: screen ./rtoolkit.sh

but i can't seem to shut it down when i go back into that screen, i have to kill the process itself (after forcing the game to save of course).

Is there an easy way of shutting down rtk? if i do: screen -r, and then 'stop', it stops and immediately restarts the game

**Comment by NeatMonster** [comment]
Does .stopwrapper work?

**Comment by ray73864** [comment]
not sure, will have to try that next time

**Comment by NeatMonster** [comment]
Because .stopwrapper is the command to use to shutdown your server. Using stop will restart your server.
