### ISSUE TITLE
Plugin configuration edits not saving

### ISSUE THREAD

**Issue by maniacmusic** [XereoNet/SpaceBukkit#124]
As mentioned in the forum there is a bug where the configuration won't save.

If I edit the pex config I hit save, then type "pex reload"
my configuration edits reset.

I'm pretty sure it used to work but now it dosn't.

**Comment by Antariano** [comment]
K, thanks for the report

**Comment by Antariano** [comment]
Silly Antariano, why do you close issues <.<

**Comment by crckdns** [comment]
It's not saving any changes made to files at the plugin-configuration menu~

and.. if you click the "save&restart" it also won't restart the server, it just posts ingame "server will restart due to changes"~ that't it

**Comment by Antariano** [comment]
thanks for the info! :)

**Comment by JamyDev** [comment]
Aaand Fixed :D
