### ISSUE TITLE
ActivationFeed needs more Blanks

### ISSUE THREAD

**Issue by Bootscreen** [XereoNet/SpaceBukkit#127]
hy,

the activation feed needs more blanks, it is horrible to read it.
this is what i see in the feed:
[2012-02-22-17-06] [BENUTZER]Bootscreen88entferntTESTvon der Whitelist
and this is what it should see, because its more readable:
[2012-02-22-17-06] [BENUTZER]Bootscreen88 entfernt TEST von der Whitelist

example screenshot:
http://imageshack.us/f/593/activationfeed.png/

**Comment by Antariano** [comment]
Will be fixed in new Dashboard, hopefully.
The issues you are having where related to the translation format being a bit buggy, though :)

**Comment by JamyDev** [comment]
Done ;)
