### ISSUE TITLE
[Suggestion] Case-Sensitive Whitelist

### ISSUE THREAD

**Issue by Bootscreen** [XereoNet/SpaceBukkit#130]
hy,

is it possible to get a case-sensitive whitelist? i know that bukkit himself makes everthing in this file to the lowercase, but this is a problem when i would show my avatar. the function of getting the avatars is case-sensitiv with Bootscreen88 i get my avatar, with bootscreen88 i doesn't get it.

i think the easiest way is a database table with case-senitive name and lowercase name so that and when i add a user to the whitelist, the scripts writes the name in the same way i write it to the case-sensitive field and write the lowercase name in the lowercasefield and the servers whitelist.

**Comment by lrenhrda** [comment]
I was just about to suggest this myself—it looks like Minotar itself is case-sensitive, so it would be a matter of working around that somehow by using Bootscreen's suggestion (or something like it), or complaining to Minotar.

Not sure which way is the "right way" though. I suppose there's a compelling argument for "however [minecraft.net](http://www.minecraft.net/) does it," which seems to be case-sensitive (skins are stored on AWS with case-sensitive names... ex.: `http://s3.amazonaws.com/MinecraftSkins/Notch.png`).

**Comment by NeatMonster** [comment]
@Bootscreen 
@lrenhrda 
We do not use Minotar anymore.

The real issue is when saving/loading the whitelist/blacklist. If the players names are saved in lowercase (by the Mc server), how can we get them with the right formatting when loading the whitelist/blacklist?

Anyways, I'll look into it. Thanks for your suggestion.

Amicably, NeatMonster.

**Comment by Bootscreen** [comment]
i know, because of this i write the second part of the suggestion about the extra table

**Comment by NeatMonster** [comment]
@Bootscreen
https://github.com/SpaceDev/SpaceBukkit/commit/d74d366e04c3fbf422ac6580e42f55fbc7b97e49
