### ISSUE TITLE
new vulnerability in spacebukkit 

### ISSUE THREAD

**Issue by N3XT0R** [XereoNet/SpaceBukkit#133]
Hello guys,

in spacebukkit is a vulnerability ;)

guests can create new users(super admins or normal users).

http://[host]/users/add

here can a guest go to the user add page and see the user add form.
So if he or she click on the submit button after fill the required fields, there
will be an exception....

but...
if they write a little html script like:

http://pastebin.com/w0XS3nLS

They can create a new admin or other user.

On submit will shown "access denied" but the user is in this moment created and a login with the new user is possible. ;)

fix it :)

**Comment by Antariano** [comment]
yep, fixed
