### ISSUE TITLE
Simple User can modify server.propertie and shedule event.

### ISSUE THREAD

**Issue by nicquehen** [XereoNet/SpaceBukkit#137]
Hello,

I add some users. 

They only have the console/player/dash access

If this user click on the link below the craftbukkit version (on the home) he can have access to the schedule/server.properties option...

**Comment by Antariano** [comment]
Thanks for the report :) Will be fixed in 1.2

**Comment by nicquehen** [comment]
Nice :D do you have an ETA ? (very impatient)

**Comment by JamyDev** [comment]
Is fixed thanks to the new roles system :D
