### ISSUE TITLE
Chat and console window only works now and then

### ISSUE THREAD

**Issue by watar** [XereoNet/SpaceBukkit#138]
Most of the time Chatwindow only says "01/01/1970 1:00:00 AM". The userlist on the right works but no chats. Console windows works a little better but is empty quite a lot of the time as well.

Using SB 1.1-01 with CB 2034.

**Comment by nicquehen** [comment]
Same problem.

Last version 1.1-01
Test on Chrom/Firefox / IE

**Comment by watar** [comment]
Not sure if this has anything to do but I just discovered that conole was unchecked on all roles under Settings - roles. After I checked this for owner and admin it seems to have gotten better. This setting must have been made upon setup because I haven't changed them before.

**Comment by watar** [comment]
Wishful thinking I guess, back to square one

**Comment by JamyDev** [comment]
I think this is fixed in 1.2
Not sure, closing for now
