### ISSUE TITLE
Idea: Checking gamemodes in Users panel

### ISSUE THREAD

**Issue by Lolmewn** [XereoNet/SpaceBukkit#14]
And maybe a button to change it. 
It's a feature, I think you should fix the bugs first but this would be nice :)

**Comment by Antariano** [comment]
Added for 1.02 (READ only, no setting yet)

**Comment by Lolmewn** [comment]
Oh cool :) Thanks.

**Comment by NeatMonster** [comment]
I added methods to set the game mode. Now waiting on @Antariano ...

**Comment by Antariano** [comment]
Reopened for 1.03 milestone

**Comment by Antariano** [comment]
Delayed to 1.04

**Comment by JamyDev** [comment]
Done, added for 1.04 :D
