### ISSUE TITLE
Looks bad on iPod

### ISSUE THREAD

**Issue by Lolmewn** [XereoNet/SpaceBukkit#140]
What it looks like: http://imgur.com/yDmo5

**Comment by crckdns** [comment]
it isn't a problem of iPod it seems, but of username-length (even if it sounds funny...)

example: 
username "cracky"  ..everything looks great, I can resize the browserwindow as I want..
username "cracky2"  .. looks same as the screen of Lolmen ..unless I resize the browser window a lot in width, then the layout looks ok again

tested with other usernames.. seems to apply to every username with length over 6 chars, independent on theme-selection

ah.. themes..another topic, found a permission-error there, will open new ticket for it.

**Comment by Antariano** [comment]
Yep, It's fixed for 1.2
