### ISSUE TITLE
YAML error

### ISSUE THREAD

**Issue by GTB3NW** [XereoNet/SpaceBukkit#144]
Issue Fixed by going into /spacemodule/players.yml and removing any erronous entries, all entries should be formatted:

name: name
and not
'name': name

etc.

21:45:33 [SEVERE] java.lang.reflect.InvocationTargetException
21:45:33 [SEVERE]       at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
21:45:33 [SEVERE]       at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
21:45:33 [SEVERE]       at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
21:45:33 [SEVERE]       at java.lang.reflect.Method.invoke(Method.java:616)
21:45:33 [SEVERE]       at me.neatmonster.spacemodule.api.ActionsManager.invoke(ActionsManager.java:90)
21:45:33 [SEVERE]       at me.neatmonster.spacemodule.api.ActionsManager.execute(ActionsManager.java:85)
21:45:33 [SEVERE]       at me.neatmonster.spacebukkit.PanelListener.interpret(PanelListener.java:47)
21:45:33 [SEVERE]       at me.neatmonster.spacebukkit.PanelListener.run(PanelListener.java:105)
21:45:33 [SEVERE] Caused by: while scanning a simple key
 in "<reader>", line 776, column 1:
    mhall
    ^
could not found expected ':'
 in "<reader>", line 777, column 1:
    woet: woet
    ^

21:45:33 [SEVERE]       at org.yaml.snakeyaml.scanner.ScannerImpl.stalePossibleSimpleKeys(ScannerImpl.java:398)
21:45:33 [SEVERE]       at org.yaml.snakeyaml.scanner.ScannerImpl.needMoreTokens(ScannerImpl.java:229)
21:45:33 [SEVERE]       at org.yaml.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:178)
21:45:33 [SEVERE]       at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingKey.produce(ParserImpl.java:563)
21:45:33 [SEVERE]       at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:161)
21:45:33 [SEVERE]       at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:146)
21:45:33 [SEVERE]       at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:230)
21:45:33 [SEVERE]       at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:160)
21:45:33 [SEVERE]       at org.yaml.snakeyaml.composer.Composer.composeDocument(Composer.java:123)
21:45:33 [SEVERE]       at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:106)
21:45:33 [SEVERE]       at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:121)
21:45:33 [SEVERE]       at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:480)
21:45:33 [SEVERE]       at org.yaml.snakeyaml.Yaml.load(Yaml.java:423)
21:45:33 [SEVERE]       at org.bukkit.util.config.Configuration.load(Configuration.java:88)
21:45:33 [SEVERE]       at me.neatmonster.spacebukkit.players.PlayerLogger.getCase(PlayerLogger.java:81)
21:45:33 [SEVERE]       at me.neatmonster.spacebukkit.actions.PlayerActions.getWhitelisted(PlayerActions.java:205)
21:45:33 [SEVERE]       ... 8 more

**Comment by ms-andy** [comment]
Could you please post the info before that?

**Comment by GTB3NW** [comment]
Just that I'm afraid. :S

**Comment by dralletje** [comment]
I had the same error, nah with other text but the same isseu.
look in your player.yml and be sure that every line has the format:
name: name

I had only
name
somehwere wich yml doesn't like.

**Comment by GTB3NW** [comment]
Ahh it's that damn fricken error where any names starting with a number are changed to 'name'. Second time that's messed up a YAML file now :/
