### ISSUE TITLE
Idea: Reset chat field when message is sent

### ISSUE THREAD

**Issue by Lolmewn** [XereoNet/SpaceBukkit#15]
The Chat field doesn't get reset when I send a message.
So for example, if I send: "Hello dudes!", it stays there. Then I have to Cntr+A + del, and I can type more stuff.
Maybe it's nicer to clear it when the message is sent.

**Comment by Antariano** [comment]
Chat system is very experimental, new one will come up eventually. 
New chat will include: Avatars, better GUI, better chat fields, inclusion of panel-sent chat messages, scrolling fix, chat field fix etc.

**Comment by Lolmewn** [comment]
Awesome. <- just like Spacebukkit.

**Comment by Antariano** [comment]
The new chat is out, 1.03 will improve it again. I'll use this issue for reference

**Comment by Antariano** [comment]
Moved to 1.04
