### ISSUE TITLE
Wont shut down and Process still runs after exit

### ISSUE THREAD

**Issue by iVMoRiginal** [XereoNet/SpaceBukkit#151]
Two issues im running into:
1. Whenever I type stop in the console, it restarts the server - not stop it :S
2. If I close the console window, the server still runs. I see it in Task Manager. I don't see any way of safely shutting down the server unless I end the process. Is there any better solution to this?

Thanks for such a great program..
iVMo

**Comment by Antariano** [comment]
Remote Toolkit is stopped with ".stopwrapper", not "stop" ;)
