### ISSUE TITLE
Command errors

### ISSUE THREAD

**Issue by Lolmewn** [XereoNet/SpaceBukkit#16]
The left thingy with the 'send a command' thingy, if you try and send a command it errors: 
Missing View

Error: The view for GlobalController::runcommand() was not found.

Error: Confirm you have created the file: D:\xampplite\htdocs\space\app\View\GlobalController\runcommand.ctp

Notice: If you want to customize this error message, create app\View\Errors\missing_view.ctp
Stack Trace
#0 D:\xampplite\htdocs\space\lib\Cake\View\View.php(363): View->_getViewFileName(NULL)
#1 D:\xampplite\htdocs\space\lib\Cake\Controller\Controller.php(900): View->render(NULL, NULL)
#2 D:\xampplite\htdocs\space\lib\Cake\Routing\Dispatcher.php(114): Controller->render()
#3 D:\xampplite\htdocs\space\lib\Cake\Routing\Dispatcher.php(89): Dispatcher->_invoke(Object(GlobalController), Object(CakeRequest), Object(CakeResponse))
#4 D:\xampplite\htdocs\space\app\webroot\index.php(96): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}

**Comment by Antariano** [comment]
fixed, thanks for the report
