### ISSUE TITLE
This happened when I logged out...

### ISSUE THREAD

**Issue by Lolmewn** [XereoNet/SpaceBukkit#17]
Not sure what caused it, but:
Warning (2): session_regenerate_id() [function.session-regenerate-id]: Session object destruction failed [CORE\Cake\Model\Datasource\CakeSession.php, line 672]

I did notice the buttons outlining was off before this error happened.

**Comment by Antariano** [comment]
where do these things come from? jeez.....

**Comment by Antariano** [comment]
Closed for 1.02 release, will be reopened in case of continued errors
