### ISSUE TITLE
cURL issue and HTTP Error 500 on step 4

### ISSUE THREAD

**Issue by hockeymikey** [XereoNet/SpaceBukkit#170]
On step 2 it says I don't have cURL enabled (using WAMP) but I infacted inabled it. (double check lots of times)  So I ignored it and went on.  When I got to step 4 I enter all my info and click next but then I get a HTTP error 500. I thought it was internet explorer so I tried Chrome but same thing.  Is it something to do with cURL?  If not what?  Thanks

**Comment by hfabc1234** [comment]
so, i think what you want to do is turn on cURl? right. thats easy. just left cilck on WAMP icon. and there should be a thing sayin PHP. and go the "php module"...  i think thats what it says.. the one under "PHP settings" you know. and then you get the list... just check "cURL" and you should be all good to go. hope that helps

**Comment by hockeymikey** [comment]
I did enable cURL ( I think you mean go under PHP Extensions not setting because cURL is not in setting) by clicking it in extensions and checking php.ini (SemiColon was removed from extension=php_curl.dll)  But it keeps saying I have to enable it after restarting WAMP and my computer too.

**Comment by hockeymikey** [comment]
Anyone have any ideas?  It still doesn't work.

**Comment by hockeymikey** [comment]
More info on my issue posted here.,

http://forums.xereo.net/threads/curl-not-enabling-on-wamp.450

**Comment by hockeymikey** [comment]
It's a problem with the 64bit version of WAMP.  The curl developers haven't fixed it for the 64v but it will work fine if you use the 32bit version.

http://forum.wampserver.com/read.php?2,85010,85010
