### ISSUE TITLE
World containers support

### ISSUE THREAD

**Issue by NeatMonster** [XereoNet/SpaceBukkit#18]
All is in the title.

**Comment by Antariano** [comment]
When do you think you're gonna be able to add this? @NeatMonster

**Comment by NeatMonster** [comment]
ASAP @Antariano. I haven't forgotten.

**Comment by NeatMonster** [comment]
I added WorldContainer support (experimental state) in the latest SpaceBukkit's builds.

Re-open this ticket if something isn't working as it should be.
