### ISSUE TITLE
Error when trying to add server to user

### ISSUE THREAD

**Issue by Lolmewn** [XereoNet/SpaceBukkit#19]
That's it.

Database Error
Error: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'user_id' cannot be null

SQL Query: INSERT INTO `servers_users` (`server_id`, `user_id`, `role_id`) VALUES (25, NULL, 4)

Notice: If you want to customize this error message, create app\View\Errors\pdo_error.ctp

Stack Trace
#0 D:\xampplite\htdocs\space\lib\Cake\Model\Datasource\DboSource.php(436): PDOStatement->execute(Array)
#1 D:\xampplite\htdocs\space\lib\Cake\Model\Datasource\DboSource.php(403): DboSource->_execute('INSERT INTO `se...', Array)
#2 D:\xampplite\htdocs\space\lib\Cake\Model\Datasource\DboSource.php(967): DboSource->execute('INSERT INTO `se...')
#3 D:\xampplite\htdocs\space\lib\Cake\Model\Model.php(1629): DboSource->create(Object(ServersUsers), Array, Array)
#4 D:\xampplite\htdocs\space\app\Controller\UsersController.php(429): Model->save(Array)
#5 [internal function]: UsersController->addToServer()
#6 D:\xampplite\htdocs\space\lib\Cake\Controller\Controller.php(473): ReflectionMethod->invokeArgs(Object(UsersController), Array)
#7 D:\xampplite\htdocs\space\lib\Cake\Routing\Dispatcher.php(107): Controller->invokeAction(Object(CakeRequest))
#8 D:\xampplite\htdocs\space\lib\Cake\Routing\Dispatcher.php(89): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest), Object(CakeResponse))
#9 D:\xampplite\htdocs\space\app\webroot\index.php(96): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#10 {main}

**Comment by Antariano** [comment]
allright, on my todo

**Comment by Antariano** [comment]
I can't replicate this issue. Does the error still occour?

**Comment by Antariano** [comment]
Closed for 1.02 release, will be reopened in case of continued errors
