### ISSUE TITLE
LOADING spacebukkit-dev-SNAPSHOT.jar as Plugin PRINTS Connection refused: connect

### ISSUE THREAD

**Issue by GoldenIrony** [XereoNet/SpaceBukkit#20]
Hi,
i followed the instructions from http://spacebukkit.xereo.net/wiki/index.php?title=Installing_SpaceBukkit
It worked fine until i configured the config.yml from spacebukkit-dev-SNAPSHOT.jar. 
Spacebukkit seems to be enable so my USER:PASS seems correct. "SpaceBukkit version 0.0.1 is now enabled!"
It seems that it results in the webinstallation in an error "The server was not reached. Please check your data."
I tried: localhost 127.0.0.1  and my local IP (in this case 192.168.0.105)
And of course my ports are 2011 & 2012 and i copied & pasted my salt. 

The Java Exception:
 java.net.ConnectException: Connection refused: connect
        at java.net.DualStackPlainSocketImpl.connect0(Native Method)
        at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source)
        at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
        at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
        at java.net.AbstractPlainSocketImpl.connect(Unknown Source)
        at java.net.PlainSocketImpl.connect(Unknown Source)
        at java.net.SocksSocketImpl.connect(Unknown Source)
        at java.net.Socket.connect(Unknown Source)
        at java.net.Socket.connect(Unknown Source)
        at sun.net.NetworkClient.doConnect(Unknown Source)
        at sun.net.www.http.HttpClient.openServer(Unknown Source)
        at sun.net.www.http.HttpClient.openServer(Unknown Source)
        at sun.net.www.http.HttpClient.<init>(Unknown Source)
        at sun.net.www.http.HttpClient.New(Unknown Source)
        at sun.net.www.http.HttpClient.New(Unknown Source)
        at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(Unknown Source)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect(Unknown Source)
        at sun.net.www.protocol.http.HttpURLConnection.connect(Unknown Source)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
        at me.neatmonster.spacebukkit.a.a.a(File:161)
        at me.neatmonster.spacebukkit.a.c.run(File:22)
        at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:137)
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:493)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:425)
        at net.minecraft.server.ThreadServerApplication.run(SourceFile:457)

My Specs:
I'm using java 32bit build 1.7.0-b147 on a Windows Vista Build 6001 
Q9500 @2,83 ghz 
4096 GB DDR2 @667mhz
P5E

**Comment by NeatMonster** [comment]
Bukkit plugin (spacebukkit-dev-SNAPSHOT.jar) can't reach the RemoteToolkit module (spacebukkitrtk-dev-SNAPSHOT.jar). Please make sure you're running RemoteToolkit using rtoolkit.bat or rtoolkit.sh. Maybe your ports aren't open too.

**Comment by GoldenIrony** [comment]
@NeatMonster  Well i made absolutly sure that the RemoteToolkit is running (used the RTKController.jar to connect to the server). And i think that it should use the proper ports. I'm not using this over the internet just on my local machine, since the firewall is turned off, so the ports should be open (don't know if you can block the local ports, but since i can login and the server says the rtk is enabled)

**Comment by NeatMonster** [comment]
@GoldenIrony When you're starting the server, can you see "Loading SpaceBukkitRTK (Licensed)...Done."?
I checked my code and as I said previously, the error is happening because the Bukkit plugin can't reach the RemoteToolkit addon. Please try opening your web browser and accessing this URL: http://localhost:<port>/call?method=ping&args=[]&key=null (replace <port> by the SpaceBukkitRTK port set in the configuration file).

**Comment by NeatMonster** [comment]
For reference, this is the unobfuscated stacktrace: http://pastie.org/3051683

**Comment by GoldenIrony** [comment]
@NeatMonster:
 Got a nice Error Message saying: "Missing Controller", when doing a :
http://localhost/spacebukkit/call?method=ping&args=[]&key=2012

(SpaceBukkitRTK: Port: 2012)

http://imageshack.us/photo/my-images/850/errorvz.png/
(sorry for the imagshack, if its not appropiate let me know i try to switch to something else)

And no, i can't see Loading SpaceBukkitRTK (Licensed)...Done. But i can see (after a while):

First attempt at checking for presence of Bukkit RTK plugin...
Bukkit RTK plugin found! Enabling heartbeats...

I waited several hours if something else happens, but nothing else than normal server blabla.

**Comment by NeatMonster** [comment]
OK. You need to install SpaceBukkitRTK which is a RemoteToolkit module. Without it, SpaceBukkit can't work. Please follow Wiki's instruction. If the module is correctly installed, you should see: "Loading SpaceBukkitRTK (Licensed)...Done.".

Sorry, the URL I gave you was wrong because GitHub formatting removed some part of it. It's http://localhost:2012/call?method=ping&args=[]&key=null if your SpaceBukkitRTK port is 2012. But please first make sure SpaceBukkitRTK is installed and working.

**Comment by davidcole1340** [comment]
This is also happening to me - I just downloaded my 3mb server log and will search for SpaceBukkitRTK.

EDIT: No, not found.

**Comment by davidcole1340** [comment]
@NeatMonster What ports need to be forwarded? I forwarded 2011 and 2012.

**Comment by NeatMonster** [comment]
@cheese5505 You won't find the line because all the RTK messages aren't written in the log file. You must open the console and start your server to see if SpaceBukkitRTK is loaded.

SpaceBukkit is only using the two ports you've defined in the configuration file.

@Antariano @JamyDev Can you remind me what website you're using to know if ports are opened?

**Comment by Antariano** [comment]
http://canyouseeme.org

**Comment by davidcole1340** [comment]
@NeatMonster That's pretty much impossible, because the sever has about 50 plugins and spacebukkit is making error messages.

**Comment by NeatMonster** [comment]
@cheese5505 Have you tried @Antariano 's website?

**Comment by davidcole1340** [comment]
@NeatMonster What's the address? xereo.net?

**Comment by NeatMonster** [comment]
@cheese5505 Look 4 posts above.

**Comment by davidcole1340** [comment]
Oh, about that. I can't. It's on a VPS.

**Comment by davidcole1340** [comment]
@NeatMonster I did it, and it diddnt work. The ports are definitely port-forwarded.

**Comment by NeatMonster** [comment]
@cheese5505 OK, but is SpaceBukkitRTK running? Please make sure the line is showed on starting. Try also to navigate to the following URL using your web browser: http://yourserverip:2012/call?method=ping&args=[]&key=null.

**Comment by hohhgames** [comment]
SpaceBukkitRTK is not running. I have installed it, and have RemoteToolkit installed and running. I proved that by using the telnet connection.

**Comment by davidcole1340** [comment]
Whoops; wrong account. The message above is from me.

**Comment by NeatMonster** [comment]
@cheese5505 Have you putted the file spacebukkitrtk-dev-SNAPSHOT.jar into the folder toolkit/modules and started the server using the rtoolkit.bat or rtoolkit.sh script?

**Comment by NeatMonster** [comment]
put*

**Comment by UserCake** [comment]
Same issue, spacebukkitrtk-dev-SNAPSHOT.jar is in the toolkit/modules folder but I get the excact same problem :S
Also, why does my licence expire 24/12/2011

**Comment by UserCake** [comment]
FIX: Shut down Remote Toolkit, then restart the vps (Well, that fixed mine anyway :) )
By the way guys... Spacebukkit is Brilliant!

**Comment by GoldenIrony** [comment]
Well placing the spacebukkitrtk-dev-SNAPSHOT. jar in the toolkit/modules fixed the problem. I was sure i placed it there -.-' Well thanks for the support. I'm moving onward to the next bug ;)

**Comment by NeatMonster** [comment]
@The8Bit @GoldenIrony Thanks guys! I'm happy to know your issues are solved.

**Comment by davidcole1340** [comment]
Yes
