### ISSUE TITLE
database.php not found Apache on Windows server

### ISSUE THREAD

**Issue by JamyDev** [XereoNet/SpaceBukkit#21]
Screenshot: http://www.myminecraft.org/screenshots/sbukkit1.png

running Apache 2.2.21, php 5.3.8 and mysql 5.5

On h0us3cat's server

**Comment by Antariano** [comment]
Closed for 1.02 release, will be reopened in case of continued errors

**Comment by h0us3cat** [comment]
On 1.0.2 
"An Internal Error Has Occurred" after filling in mysql step
in log

2011-12-22 18:05:05 Error: [MissingConnectionException] Database connection "Mysql" is missing, or could not be created.
#0 C:\sites\mysite\sbukkit\app\Model\ConnectionManager.php(98): DboSource->__construct(Array)
#1 C:\sites\mysite\sbukkit\app\Controller\InstallController.php(215): ConnectionManager::getDataSource('default')
#2 [internal function]: InstallController->step2()
#3 C:\sites\mysite\sbukkit\lib\Cake\Controller\Controller.php(473): ReflectionMethod->invokeArgs(Object(InstallController), Array)
#4 C:\sites\mysite\sbukkit\lib\Cake\Routing\Dispatcher.php(107): Controller->invokeAction(Object(CakeRequest))
#5 C:\sites\mysite\sbukkit\lib\Cake\Routing\Dispatcher.php(89): Dispatcher->_invoke(Object(InstallController), Object(CakeRequest), Object(CakeResponse))
#6 C:\sites\mysite\sbukkit\app\webroot\index.php(96): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#7 {main}

**Comment by NeatMonster** [comment]
@Antariano Please take a look at @h0us3cat 's error.

**Comment by Antariano** [comment]
@h0us3cat please make sure  pdo_mysql is loaded in your php.ini file

**Comment by h0us3cat** [comment]
@Antariano 

it works!
