### ISSUE TITLE
cURL is not on

### ISSUE THREAD

**Issue by davidcole1340** [XereoNet/SpaceBukkit#22]
I have enabled cURL but, it still says cURL is not enabled. Any ideas why?

**Comment by JamyDev** [comment]
If your on linux you also have to apt-get install lib-curl
On Dec 20, 2011 8:36 PM, "cheese5505" <
reply@reply.github.com>
wrote:

**Comment by NeatMonster** [comment]
Left click on the WAMP icon > PHP > php.ini. Search for this line: ";extension=php_curl.dll" and remove the " ; ". Save the file > Restart all services.

**Comment by davidcole1340** [comment]
I did that, but I found the issue. You go to WAMP icon > PHP > PHP Extentions > php_curl
