### ISSUE TITLE
Is it me or is the RAM meter off?

### ISSUE THREAD

**Issue by Lolmewn** [XereoNet/SpaceBukkit#23]
It jumps from 20 -> -> -> -> somewhere around 90, then back to 20 and then it starts all over again (the count, not the server).

**Comment by NeatMonster** [comment]
I'm using this code to get the RAM usage:
Runtime.getRuntime().totalMemory() - Runtime.getRuntime().freeMemory();
If you know an other way to get the RAM usage, please post it here.

**Comment by NeatMonster** [comment]
JSONAPI use exactly the same code as me.
https://github.com/alecgorge/jsonapi/blob/master/src/com/alecgorge/minecraft/jsonapi/dynamic/APIWrapperMethods.java#L703
