### ISSUE TITLE
Says server is offline, but it is not.

### ISSUE THREAD

**Issue by davidcole1340** [XereoNet/SpaceBukkit#24]
When I get to the enter server page on the setup, I type in my details, press next but it says that the details are incorrect. The server IS up, but it wont register.

**Comment by davidcole1340** [comment]
Anyone know why??

**Comment by GoldenIrony** [comment]
@cheese5505: Look at my issue i have the same Problem maybe it can help

https://github.com/NeatMonster/SpaceBukkit/issues/20

**Comment by NeatMonster** [comment]
See #20.
