### ISSUE TITLE
Plugin Tab Crashed Panel

### ISSUE THREAD

**Issue by dst1980** [XereoNet/SpaceBukkit#25]
When I attempt to use the Plugins panel I get the following error in the console promptly after clicking the "Plugins" button:
20:38:11 [SEVERE] Exception in thread "Thread-474224" 
20:38:11 [SEVERE] java.lang.ExceptionInInitializerError
20:38:11 [SEVERE]       at a.a.a.b.<init>(File:41)
20:38:11 [SEVERE]       at a.a.b.a(File:41)
20:38:11 [SEVERE]       at me.neatmonster.spacebukkit.a.a.a(File:260)
20:38:11 [SEVERE]       at me.neatmonster.spacebukkit.c.c.a(File:113)
20:38:11 [SEVERE]       at me.neatmonster.spacebukkit.c.c.a(File:45)
20:38:11 [SEVERE]       at me.neatmonster.spacebukkit.b.b.run(File:57)
20:38:11 [SEVERE] Caused by: java.lang.ArrayIndexOutOfBoundsException: 65536
20:38:11 [SEVERE]       at a.a.a.e.<clinit>(File:43)
20:38:11 [SEVERE]       ... 6 more

The server then has to be restarted through the console "stop" command before SpaceBukkit will do anything further.
The plugins that are installed are:
MinecraftRKitPlugin.jar
spacebukkit-dev-SNAPSHOT.jar

**Comment by Lolmewn** [comment]
Yep, same.

**Comment by Antariano** [comment]
In 1.02 the java plugins will be updated to hopefully fix those issues

**Comment by NeatMonster** [comment]
This is the unobfuscated stacktrace: http://pastie.org/3051666.
Please try v1.02 (when it'll be released) and tell me if the error is still occurring.

**Comment by dst1980** [comment]
I look forward to the next update.

**Comment by Antariano** [comment]
should be out in 1 hour
