### ISSUE TITLE
Can't access the installation panel

### ISSUE THREAD

**Issue by ghost** [XereoNet/SpaceBukkit#28]
I recently downloaded the version 1.0.2 of SpaceBukkit, removed the old version and replaced it with the new one.
I also replaced the plugins and the rtk file from the server with the new ones.

As soon as I tried to access the SpaceBukkit installation page, I got this issue.

"Not Found

The requested URL /SpaceBukkit/install was not found on this server.
Apache/2.2.15 (CentOS) Server at www.nextgenminecraft.net Port 80"

I made sure all the files told in the installation video were writable and every settings we're correct, and they are.
The mod_rewrite is enabled, allow_url_fopen is on and the CURL is enabled.

**Comment by Antariano** [comment]
is "AllowOverride All" enabled in your http.conf ?

**Comment by ghost** [comment]
Ah, it was set as AllowOverride None. Changed it to All instead and now it works.
Thanks!
