### ISSUE TITLE
SpaceBukkit Crashed after clicking the Plugin Page

### ISSUE THREAD

**Issue by GoldenIrony** [XereoNet/SpaceBukkit#29]
Well after it now does work, i installed it and looked a lil bit around. I chatted a bit and tried to look who is on the server etc. After i clicked the plugin page he loaded for a while... and didn't stop. A quick look into the console showed me this:

12:38:24 [WARNING] ----------------------------------------------------------
12:38:24 [WARNING] |  Unallowed connection detected! No method, wrong args? |
12:38:24 [WARNING] ----------------------------------------------------------
12:38:24 [WARNING] ----------------------------------------------------------
12:38:24 [WARNING] |  Unallowed connection detected! No method, wrong args? |
12:38:24 [WARNING] ----------------------------------------------------------
12:38:24 [WARNING] ----------------------------------------------------------
12:38:24 [WARNING] |  Unallowed connection detected! No method, wrong args? |
12:38:24 [WARNING] ----------------------------------------------------------
12:38:25 [WARNING] ----------------------------------------------------------
12:38:25 [WARNING] |  Unallowed connection detected! No method, wrong args? |
12:38:25 [WARNING] ----------------------------------------------------------
First attempt at checking for presence of Bukkit RTK plugin...
Bukkit RTK plugin found! Enabling heartbeats...
12:42:54 [INFORMATION] [SpaceBukkit] super: dood
12:43:54 [SCHWERWIEGEND] Exception in thread "Thread-584"
12:43:54 [SCHWERWIEGEND] java.lang.ExceptionInInitializerError
12:43:54 [SCHWERWIEGEND]        at a.a.a.b.<init>(File:41)
12:43:54 [SCHWERWIEGEND]        at a.a.b.a(File:41)
12:43:54 [SCHWERWIEGEND]        at me.neatmonster.spacebukkit.a.a.a(File:260)
12:43:54 [SCHWERWIEGEND]        at me.neatmonster.spacebukkit.c.c.a(File:113)
12:43:54 [SCHWERWIEGEND]        at me.neatmonster.spacebukkit.c.c.a(File:45)
12:43:54 [SCHWERWIEGEND]        at me.neatmonster.spacebukkit.b.b.run(File:57)
12:43:54 [SCHWERWIEGEND] Caused by: java.lang.ArrayIndexOutOfBoundsException: 65536
12:43:54 [SCHWERWIEGEND]        at a.a.a.e.<clinit>(File:43)
12:43:54 [SCHWERWIEGEND]        ... 6 more
12:44:01 [INFORMATION] /127.0.0.1:49719 lost connection

Note: (nothing to do with this): After restarting (to replicate the bug) the chatlog was still showing the "dood" i wrote before server crashed (thats cool but i'm not sure if bug or not)

Note2: (What does "Unallowed connection detected! No method, wrong args?" mean? Seems not issue relevant...)

**Comment by NeatMonster** [comment]
For reference, this is the unobfuscated stacktrace: http://pastie.org/3057672

Please update SpaceBukkit to v1.02: the panel AND the two .JARs.

Reopen the ticket if the issue is still there in v1.02.

**Comment by GoldenIrony** [comment]
@NeatMonster: Am I blind, i can't find a download for (Spacebukkit Plugin v1.02) this? Is this because of only 93% finished?

**Comment by NeatMonster** [comment]
@GoldenIrony Please at least search on the forums: http://spacebukkit.xereo.net/forum/index.php?topic=32.msg137;boardseen#new
