### ISSUE TITLE
Can't change theme trough settings->Theme's

### ISSUE THREAD

**Issue by Lolmewn** [XereoNet/SpaceBukkit#3]
Doesn't have a button for it, soo..
It can be done through hovering over my name->Spacebukkit Theme->Activate

**Comment by Lolmewn** [comment]
Oh, I just noticed.
name->Spacebukkit Theme has an error in the background:

Notice (8): Undefined variable: current_user [APP\View\Users\theme.ctp, line 2]
Code Context
include - APP\View\Users\theme.ctp, line 2
View::_render() - CORE\Cake\View\View.php, line 598
View::render() - CORE\Cake\View\View.php, line 365
Controller::render() - CORE\Cake\Controller\Controller.php, line 900
Dispatcher::_invoke() - CORE\Cake\Routing\Dispatcher.php, line 114
Dispatcher::dispatch() - CORE\Cake\Routing\Dispatcher.php, line 89
[main] - APP\webroot\index.php, line 96

**Comment by JamyDev** [comment]
I think this is intentional because in previous versions we enabled themes through settings :)

**Comment by Antariano** [comment]
The themes on the settings page are for managing them (e.g. deleting and installing)

**Comment by Antariano** [comment]
Fixed error in background (also appearing in "edit user" from the settings page.)
