### ISSUE TITLE
SpaceBukkit Crashed after adding a User in the Blacklist

### ISSUE THREAD

**Issue by GoldenIrony** [XereoNet/SpaceBukkit#30]
Tried to add a User with Random Name to the Blacklist. Again the Page is forever loading and in the console this error:

13:20:58 [SCHWERWIEGEND] Exception in thread "Thread-1066"
13:20:58 [SCHWERWIEGEND] java.lang.NullPointerException
13:20:58 [SCHWERWIEGEND]        at org.bukkit.craftbukkit.CraftServer.getPlayer(CraftServer.java:230)
13:20:58 [SCHWERWIEGEND]        at org.bukkit.Bukkit.getPlayer(Bukkit.java:115)
13:20:58 [SCHWERWIEGEND]        at me.neatmonster.spacebukkit.c.c.a(File:53)
13:20:58 [SCHWERWIEGEND]        at me.neatmonster.spacebukkit.c.c.a(File:45)
13:20:58 [SCHWERWIEGEND]        at me.neatmonster.spacebukkit.b.b.run(File:57)

EDITED: Hm something strange happend after restarting the server, he said that the User was added to the blacklist, but he was not

**Comment by Antariano** [comment]
Thanks, we'll fix this.

**Comment by NeatMonster** [comment]
For reference, this is the unobuscated stacktrace: http://pastie.org/3057655

**Comment by Antariano** [comment]
@NeatMonster does the ban only work on people that we're on the server?

**Comment by NeatMonster** [comment]
@GoldenIrony Please try: http://dl.dropbox.com/u/34835222/SpaceBukkit/latest.zip

**Comment by JamyDev** [comment]
Found issue, fixed for 1.04
