### ISSUE TITLE
Idea: Adding a application form and a forum.

### ISSUE THREAD

**Issue by GoldenIrony** [XereoNet/SpaceBukkit#31]
Well this may not be new and maybe planned. 

This feature is easy: You can go to the formal adress of a server and write an application form in Spacebukkit. The Admin will get a notification and can unlock him so he can join the server.

I know there are auth features in Bukkit and SpacBukkit but i want a central place where I can control all the users on my server. 

Also the inbuild Bukkit doesn't seem to work (never used it so i guess since there auth plugins.. it never worked to begin with so a real whitelist would be nice - i need it). 

After that i want to add a feature to spacebukkit (mayb only a Reflink) like a forum and a blog and maybe a video canal and something else. The can be Videos can be hosted elsewhere. 

Any feedback from anyone is desired.

**Comment by Lolmewn** [comment]
I have this in-game, as plugin.
Might release it, not sure.

**Comment by GoldenIrony** [comment]
@Lolmen: I found AuthDB (http://wiki.bukkit.org/AuthDB) which writes them into a MySQL database. Would stil require updating (I don't know MySQL, only MSSQL. Can you build a trigger or maybe something like a Stored Procedure for this?). I also want a ref link for dynmap, @Antariano (you) said there might be a support for dynmap later, but i would be glad about a localhost:8123 reference.

**Comment by Lolmewn** [comment]
@GoldenIrony you can test mine out in my server :)
Join mc.centrility.nl and type /apply

**Comment by GoldenIrony** [comment]
@Lolmen; This is really neat i like it. Is there a way to do a interaction? Like giving them some stone saying build this, or do this and look how well it is done?

**Comment by Lolmewn** [comment]
@GoldenIrony Don't think that is possible through a plugin..
And don't really want to add that anyway :)

**Comment by GoldenIrony** [comment]
@Lolmen  Ok :) Well maybe i'm going to search (when there is nothing i will write) a plugin which can do that to a limited extent (i like the idea of a tutorial as an application form).

**Comment by Antariano** [comment]
Closed since I have no idea if we add this before Sputnik
