### ISSUE TITLE
Idea: Scripted Commands bind on a button which can be placed on control Panel

### ISSUE THREAD

**Issue by GoldenIrony** [XereoNet/SpaceBukkit#32]
Same here i don't know if its planned.It would be nice if i could add a button and place them on a control panel with scripted commands. 

EDITED: LOL found the console for making commands (first idea was to make that avaible over chatbox, but this is even better)

**Comment by Antariano** [comment]
This is planned with our Addon system, due for the full release of the panel (after beta)
