### ISSUE TITLE
Init Failure after restart

### ISSUE THREAD

**Issue by GoldenIrony** [XereoNet/SpaceBukkit#33]
After a failure i restartet my Server and got this: 
14:07:38 [SCHWERWIEGEND] Exception in thread "Thread-7"
14:07:38 [SCHWERWIEGEND] java.lang.ExceptionInInitializerError
14:07:38 [SCHWERWIEGEND]        at a.a.a.b.<init>(File:41)
14:07:38 [SCHWERWIEGEND]        at a.a.b.a(File:41)
14:07:38 [SCHWERWIEGEND]        at me.neatmonster.spacebukkit.a.a.a(File:260)
14:07:38 [SCHWERWIEGEND]        at me.neatmonster.spacebukkit.c.c.a(File:113)
14:07:38 [SCHWERWIEGEND]        at me.neatmonster.spacebukkit.c.c.a(File:45)
14:07:38 [SCHWERWIEGEND]        at me.neatmonster.spacebukkit.b.b.run(File:57)
14:07:38 [SCHWERWIEGEND] Caused by: java.lang.ArrayIndexOutOfBoundsException: 65536
14:07:38 [SCHWERWIEGEND]        at a.a.a.e.<clinit>(File:43)
14:07:38 [SCHWERWIEGEND]        ... 6 more

**Comment by NeatMonster** [comment]
For reference, this is the unobfuscated stacktrace.

Please update to v1.02. See also #29.
