### ISSUE TITLE
Idea: Customize the server list

### ISSUE THREAD

**Issue by Lolmewn** [XereoNet/SpaceBukkit#35]
And with Customize, I mean put them in another order.
I put my TestServer in first (to test, duhh), and then my main.
But I use it way more often for my main server.. so maybe an option to change the order of the servers would be nice.

**Comment by Antariano** [comment]
I'll look into it

**Comment by Antariano** [comment]
Would "favorite server" be enough for now? (Set's the server that get's loaded on login)

**Comment by Lolmewn** [comment]
Ye it will :)

**Comment by Antariano** [comment]
Moved to 1.04

**Comment by NeatMonster** [comment]
Any update on this issue?

**Comment by Antariano** [comment]
I'm on it

**Comment by Antariano** [comment]
Added.
