### ISSUE TITLE
Idea: Keep servers and users on Update

### ISSUE THREAD

**Issue by Lolmewn** [XereoNet/SpaceBukkit#36]
Since you have to do a clean update every time, all users and servers get lost and have to be re-made.
Well, as a server admin of 3 servers, that takes some time to set up.

Maybe it would be nice to store them in the MySQL server and check if there's any data in there on the install.

**Comment by Antariano** [comment]
It's not a standard thing, it's just for closed beta, an updater is already scripted, so for future update you'll use that one.

**Comment by Lolmewn** [comment]
Nice. Thanks.
Any clue when this.. Updater will be in?

**Comment by Antariano** [comment]
For the next update :)
