### ISSUE TITLE
Schedule is way off

### ISSUE THREAD

**Issue by Lolmewn** [XereoNet/SpaceBukkit#37]
This is in my scheduler:
5   Say something   Server restarting in 5 minutes! Once per day at X:Y 3 : 55
It fired just now. And it's 20:11. It's supposed to fire at 3:55 AM. 
That's just not right!

**Comment by JamyDev** [comment]
What timezone is minecraft server set to?

**Comment by Lolmewn** [comment]
Oh wait. It might be RTK doing this.
_more testing_
