### ISSUE TITLE
Messages with a : in it fail

### ISSUE THREAD

**Issue by Lolmewn** [XereoNet/SpaceBukkit#38]
Everything behind the : gets removed.
That's all.

**Comment by JamyDev** [comment]
Messages get send completely, but the new chat only shows untill the :

**Comment by NeatMonster** [comment]
@Lolmen Is this also happening for the messages displayed in-game? (Messages sent from SpaceBukkit.)

**Comment by Antariano** [comment]
it is due to a fail on my part, sorry about that. I'll fix it (new chat is experimental and still WIP)

**Comment by Antariano** [comment]
fixed
