### ISSUE TITLE
V1.0.2 - Plugins gives error and still freeze web-end

### ISSUE THREAD

**Issue by Lolmewn** [XereoNet/SpaceBukkit#39]
This is the error I get in console:

21:27:53 [SEVERE] Exception in thread "Thread-4382"
21:27:53 [SEVERE] java.lang.NoSuchMethodError: org.json.JSONArray.size()I
21:27:53 [SEVERE]       at me.neatmonster.spacebukkit.utilities.Utilities.getBukkitDevName(Utilities.java:265)
21:27:53 [SEVERE]       at me.neatmonster.spacebukkit.web.Executor.getPluginInformations(Executor.java:608)
21:27:53 [SEVERE]       at me.neatmonster.spacebukkit.web.Interpretator.checkMethod(Interpretator.java:113)
21:27:53 [SEVERE]       at me.neatmonster.spacebukkit.web.Interpretator.interpret(Interpretator.java:45)
21:27:53 [SEVERE]       at me.neatmonster.spacebukkit.listeners.Listener.run(Listener.java:57)

And the web-end still freezes after.

**Comment by NeatMonster** [comment]
@Lolmen What's your Java version?

**Comment by Lolmewn** [comment]
Both web-end and plugin end are (as far as I know) Java 7.

**Comment by Antariano** [comment]
Could you enlist your plugins please?

**Comment by Lolmewn** [comment]
Here's a picture: http://dl.dropbox.com/u/7365249/ScreenShot007.bmp

Edit: NOTE: Some are my own, custom :)

**Comment by NeatMonster** [comment]
@Lolmen Please update Panel, Module and Plugin to v1.03 and tell me the issue is still there.

Download latest version of Module/Plugin: http://dl.dropbox.com/u/34835222/SpaceBukkit/latest.zip

**Comment by Lolmewn** [comment]
Ill try when I have time.

**Comment by NeatMonster** [comment]
@Lolmen OK, I really don't know where this issue comes from. It looks like one of the internal methods of Java (.size() on an List) isn't found. Weird...

**Comment by JamyDev** [comment]
Try if 1.04 fixes your issue ;)

**Comment by JamyDev** [comment]
Ok 1.04 didn't fix it ..

**Comment by Lolmewn** [comment]
Nop :) 23:07:02 [SEVERE] Exception in thread "Thread-184"
23:07:02 [SEVERE] java.lang.NoClassDefFoundError: Could not initialize class a.a.a.e
23:07:02 [SEVERE]       at a.a.a.b.<init>(File:41)
23:07:02 [SEVERE]       at a.a.c.a(File:41)
23:07:02 [SEVERE]       at a.a.c.a(File:51)
23:07:02 [SEVERE]       at me.neatmonster.spacebukkit.a.a.a(File:278)
23:07:02 [SEVERE]       at me.neatmonster.spacebukkit.c.c.a(File:113)
23:07:02 [SEVERE]       at me.neatmonster.spacebukkit.c.c.a(File:45)
23:07:02 [SEVERE]       at me.neatmonster.spacebukkit.b.c.run(File:57)

**Comment by NeatMonster** [comment]
Fixed! http://dl.dropbox.com/u/34835222/SpaceBukkit/latest.zip

**Comment by NeatMonster** [comment]
I finally fixed this issue, damned Minequery.

http://dl.dropbox.com/u/34835222/SpaceBukkit/latest.zip

**Comment by Lolmewn** [comment]
Yep, thanks :D

**Comment by NeatMonster** [comment]
You're welcome!
