### ISSUE TITLE
V1.0.1 won't install

### ISSUE THREAD

**Issue by Lolmewn** [XereoNet/SpaceBukkit#4]
After step 3 (the one with the ports) it gives
object(File)#24 (6) { ["Folder"]=> object(Folder)#26 (7) { ["path"]=> string(37) "D:\xampplite\htdocs\space\app\webroot" ["sort"]=> bool(false) ["mode"]=> int(493) ["_messages":protected]=> array(0) { } ["_errors":protected]=> array(0) { } ["_directories":protected]=> NULL ["_files":protected]=> NULL } ["name"]=> string(8) "inst.txt" ["info"]=> array(0) { } ["handle"]=> NULL ["lock"]=> NULL ["path"]=> string(46) "D:\xampplite\htdocs\space\app\webroot\inst.txt" }

I'm on Windows, using XAMPP.

**Comment by JamyDev** [comment]
Did you wipe everything?

**Comment by Antariano** [comment]
Yes, I'm on it. V1.02 will include another bunch of fixes... Does v1.00 work?

**Comment by Lolmewn** [comment]
Yep, 1.0.0 did work. And of course I wiped it :)

**Comment by Antariano** [comment]
Guess what it was... lol I forgot to delete my debugging declarations :)

**Comment by Lolmewn** [comment]
Oh you! :)

**Comment by Antariano** [comment]
I'll close this for now, we'll reopen it if installer won't work again
