### ISSUE TITLE
Error on dashboard

### ISSUE THREAD

**Issue by UserCake** [XereoNet/SpaceBukkit#40]
Hey,
I installed spacebukkit 1.0.2, but on the dashboard I get this error above the page (I have to scroll down to see spaebukkit)
LONG ERROR ALERT!
Warning (2): in_array() expects parameter 2 to be array, null given [APP/Controller/DashController.php, line 176]
Warning (2): in_array() expects parameter 2 to be array, null given [APP/Controller/DashController.php, line 176]
Warning (2): in_array() expects parameter 2 to be array, null given [APP/Controller/DashController.php, line 176]
Warning (2): in_array() expects parameter 2 to be array, null given [APP/Controller/DashController.php, line 176]
Warning (2): in_array() expects parameter 2 to be array, null given [APP/Controller/DashController.php, line 176]
Warning (2): in_array() expects parameter 2 to be array, null given [APP/Controller/DashController.php, line 176]
Warning (2): in_array() expects parameter 2 to be array, null given [APP/Controller/DashController.php, line 176]
Code Context
$id =   "24"
$getserver  =   array(
    "Server" => array(
    "id" => "24",
    "title" => "C.H.A.O.S.",
    "address" => "199.167.135.243",
    "password" => "*****",
    "port1" => "2011",
    "port2" => "2010",
    "default_role" => "1"
),
    "ServersUsers" => array()
)
$server =   null
$salt   =   "C.H.A.O.S."
$p1 =   "2011"
$p2 =   "2010"
$api    =   SpaceBukkitAPI
SpaceBukkitAPI::$host = "199.167.135.243"
SpaceBukkitAPI::$port1 = "2011"
SpaceBukkitAPI::$port2 = "2010"
SpaceBukkitAPI::$salt = "C.H.A.O.S."
$args   =   array()
$running    =   true
$sbconf =   array(
    "app_version" => "Closed Beta v1.02",
    "app" => "6",
    "theme" => "Spacebukkit"
)
$languages  =   array(
    "English" => "eng"
)
$permissions    =   array(
    "pages" => array(
    "dash" => 1,
    "users" => 2,
    "plugins" => 4,
    "worlds" => 8,
    "server" => 16,
    "servertools" => 32,
    "console" => 64
),
    "global" => array(
    "addRemoveServer" => 1,
    "stopStartServer" => 2,
    "reloadServer" => 4,
    "restartServer" => 8,
    "vanillaMode" => 16,
    "configureServer" => 32
),
    "dash" => array(
    "seeConsole" => 1,
    "runCommand" => 2,
    "Activity" => 4,
    "Chat" => 8,
    "Stats" => 16
),
    "users" => array(
    "healAndFeed" => 1,
    "kill" => 2,
    "seeInventory" => 4,
    "kick" => 8,
    "ban" => 16,
    "whitelist" => 32,
    "op" => 64,
    "editInventory" => 128
),
    "plugins" => array(
    "disablePlugin" => 1,
    "removeAddPlugin" => 2,
    "configurePlugin" => 4,
    "removeAddAddons" => 8,
    "updatePlugin" => 16
),
    "worlds" => array(
    "runChunkster" => 1,
    "runMapAutoTrim" => 2
),
    "servers" => array(
    "addRemoveShedule" => 1,
    "changeBukkit" => 2
),
    "settings" => array(
    "seeUsers" => 1,
    "editUser" => 2,
    "addRemoveUser" => 4,
    "seeRoles" => 8,
    "addRemoveRoles" => 16,
    "editRoles" => 32,
    "seeThemes" => 64,
    "installRemoveTheme" => 128,
    "editSpaceBukkit" => 256
)
)
$c_bukkit_version   =   ""
$filename   =   "http://ci.bukkit.org/other/latest_recommended.rss"
$http_response_header   =   array(
    "HTTP/1.1 200 OK",
    "Server: nginx/1.0.4",
    "Date: Thu, 22 Dec 2011 21:00:53 GMT",
    "Content-Type: application/rss+xml",
    "Content-Length: 7859",
    "Last-Modified: Thu, 22 Dec 2011 21:00:02 GMT",
    "Connection: close",
    "Accept-Ranges: bytes"
)
$load_bukkit_version    =   SimpleXMLElement
SimpleXMLElement::$@attributes = array
SimpleXMLElement::$channel = SimpleXMLElement object
$link_to_latest =   SimpleXMLElement

$l_bukkit_version   =   "1597"
$m_bukkit_version   =   "<p class="cell_small fail">Outdated!</p>"
$plugin_count   =   0
$dis_plugin_count   =   0
$current_server_id  =   array(
    "Server" => array(
    "id" => "24",
    "title" => "C.H.A.O.S.",
    "address" => "199.167.135.243",
    "password" => "*****",
    "port1" => "2011",
    "port2" => "2010",
    "default_role" => "1"
),
    "ServersUsers" => array()
)
$connected_users    =   0
$worlds =   array(
    "Normal",
    "FlatLands",
    "Normal_nether",
    "Nogrief",
    "Normal_the_end",
    "Creative",
    "Survival"
)
$loadedWorlds   =   null
$worlds_count   =   array(
    "normal" => 0,
    "nether" => 0,
    "sky" => 0,
    "end" => 0
)
$w  =   "Survival"
in_array - [internal], line ??
DashController::index() - APP/Controller/DashController.php, line 176
ReflectionMethod::invokeArgs() - [internal], line ??
Controller::invokeAction() - CORE/Cake/Controller/Controller.php, line 473
Dispatcher::_invoke() - CORE/Cake/Routing/Dispatcher.php, line 107
Dispatcher::dispatch() - CORE/Cake/Routing/Dispatcher.php, line 89
[main] - APP/webroot/index.php, line 96

Thanks,
_8Bit

**Comment by Antariano** [comment]
How many worlds do you have on your server?

**Comment by UserCake** [comment]
3, 2 creative, 1 survival

**Comment by Antariano** [comment]
Ok, 1.03 hopefully will fix this.

**Comment by UserCake** [comment]
Thanks

**Comment by Antariano** [comment]
Should be fixed now, if "loadedWorlds" is not an array, it get's resetted to an empty array, preventing the error.
