### ISSUE TITLE
Can't make superuser when adding new user

### ISSUE THREAD

**Issue by Lolmewn** [XereoNet/SpaceBukkit#41]
Title says it all I think.
I can add ppl, but the button of SuperUser is not there.
When I click edit, I can click it though.

**Comment by acertain** [comment]
there is only one superuser.

**Comment by Antariano** [comment]
Thanks, i probably missed it.
@fread2281 Actually "SuperUser" means you get all rights and access to the "Settings" page, so they are unlimited.

**Comment by JamyDev** [comment]
Fixed in 1.04 :D
