### ISSUE TITLE
Bukget filter by 0-9 A...Z is multiplying

### ISSUE THREAD

**Issue by GoldenIrony** [XereoNet/SpaceBukkit#42]
Well i can't explain this bug good so you get an Image, also it is not so important. 
Well when i try to click i he gives me a new row of A-9 A..Z and again and again. 

Found in Spacebukkit v1.02

http://imageshack.us/photo/my-images/196/erroruq.png/

**Comment by Antariano** [comment]
Thanks for your notification, I'm on it

**Comment by JamyDev** [comment]
BukGet is down atm, I'll fix it once it's back up; This could be after 1.04..
Moved this for 1.05

**Comment by JamyDev** [comment]
Moving to 1.05 due to BukGet downtime

**Comment by JamyDev** [comment]
Can't seem to reproduce the error anymore; What browser did you use?
