### ISSUE TITLE
Clicking on Save & Restart Server in the Configure Plugin Dialogue kills SpaceBukkit

### ISSUE THREAD

**Issue by GoldenIrony** [XereoNet/SpaceBukkit#43]
I installed over bukget iConomy, restarted my Server and tried over the Configure Plugin to configure it. Worked so fine, after i clicked on Save & Restart. The website crashes, the server sometimes restarts fine. After i restart my server manually the website works again. The Save & Reload function does not throw this error. 

I get this Error on the Page:
Notice (8): Undefined variable: args2 [APP\Controller\TpluginsController.php, line 334]

And in the console of the Bukkit server following:
java.io.FileNotFoundException: plugins\iConomy\Config.yml (Der Vorgang ist bei einer Datei mit einem geöffneten Bereich, der einem Benutzer zugeordnet ist, nicht anwendbar)
        at java.io.FileOutputStream.open(Native Method)
        at java.io.FileOutputStream.<init>(Unknown Source)
        at java.io.FileOutputStream.<init>(Unknown Source)
        at java.io.FileWriter.<init>(Unknown Source)
        at me.neatmonster.spacebukkitrtk.web.Executor.setFileContents(Executor.java:375)
        at me.neatmonster.spacebukkitrtk.web.Interpretator.checkMethod(Interpretator.java:71)
        at me.neatmonster.spacebukkitrtk.web.Interpretator.interpret(Interpretator.java:33)
        at me.neatmonster.spacebukkitrtk.listeners.Listener.run(Listener.java:71)
19:34:13 [SEVERE] Exception in thread "Thread-229"
19:34:13 [SEVERE] java.lang.NullPointerException
19:34:13 [SEVERE]       at me.neatmonster.spacebukkit.web.Interpretator.checkMethod(Interpretator.java:58)
19:34:13 [SEVERE]       at me.neatmonster.spacebukkit.web.Interpretator.interpret(Interpretator.java:45)
19:34:13 [SEVERE]       at me.neatmonster.spacebukkit.listeners.Listener.run(Listener.java:57)
19:38:44 [INFO] GoldenIrony [/127.0.0.1:50372] logged in with entity id 140 at ([world] 1134.28125, 62.0, 490.84375)    

I checked the Config.yml it is in ther right place and Bukkit has root rights. (Its on my test machine of course) 

Specs usual:

Spacebukkit v1.02
Bukkit 1597
Windows Vista Build 6001 
Xampp

**Comment by Antariano** [comment]
Thanks for reporting this

**Comment by NeatMonster** [comment]
@Antariano Try using .\plugins instead of \plugins.

**Comment by NeatMonster** [comment]
@GoldenIrony Can you try again with latest builds please? http://dl.dropbox.com/u/34835222/SpaceBukkit/latest.zip
