### ISSUE TITLE
Save And Save & Reload does not work properly (Configure Plugin)

### ISSUE THREAD

**Issue by GoldenIrony** [XereoNet/SpaceBukkit#44]
I installed iConomy over Bukget and tried to configure it at the Plugin page. After the windows pops up i press Save, but the actual file is not being modified. Same for Save & Reload. SpaceBukkit reloads the Server but does not keep the change. 
Funny thing is that after i saved it and configure it again it showed me the change i made. Also it showed me the change in the file. But i have to go to the Plugin page (i even don't know why i got back to the dashboard, after i saved my changes and not to the Plugin Page - very useless if i want to configure a lot of plugins.) and click on configure again.  

Specs:
Spacebukkit v1.02
Bukkit 1597
Windows Vista Build 6001
Xampp

**Comment by Antariano** [comment]
Thanks for the notification, the redirect is probably a fail of mine

**Comment by NeatMonster** [comment]
@GoldenIrony Can you try again with latest builds please? http://dl.dropbox.com/u/34835222/SpaceBukkit/latest.zip

**Comment by JamyDev** [comment]
Should be fixed, if not by NeatMonster
