### ISSUE TITLE
Plugin Search seems to be in the wrong place 

### ISSUE THREAD

**Issue by GoldenIrony** [XereoNet/SpaceBukkit#45]
It is just wrong placed and will be fixed in the new version or is it just me?

http://imageshack.us/photo/my-images/269/errorkcj.png/

Specs usual:

Spacebukkit v1.02
Bukkit 1597
Windows Vista Build 6001
Xampp

**Comment by Antariano** [comment]
It is bugged, especially on firefox. Thanks for the report

**Comment by JamyDev** [comment]
Fixed in 1.04
