### ISSUE TITLE
Plugin is not disabled after clicking Disable

### ISSUE THREAD

**Issue by GoldenIrony** [XereoNet/SpaceBukkit#46]
I can click disable and nothing changes, i can click it again and again but nothing will happen. (If i disabled a Plugin shouldn't I be able to enable it afterwards?) . Also nothing happens to the status and it is not disabled in Bukkit. Also nothing is happening if i reload or restart the Server. 

Specs usual:

Spacebukkit v1.02
Bukkit 1597
Windows Vista Build 6001
Xampp

**Comment by Antariano** [comment]
Thanks, we'll look into it

**Comment by NeatMonster** [comment]
@GoldenIrony I made some changes to my code but it may not fix your issue.
Download the latest version: http://dl.dropbox.com/u/34835222/SpaceBukkit/latest.zip

**Comment by JamyDev** [comment]
Try 1.04 and check if this fixes your issue please ;)

**Comment by JamyDev** [comment]
Closed, should work now, if not please post ;)
