### ISSUE TITLE
Idea: Localize SpaceBukkit

### ISSUE THREAD

**Issue by GoldenIrony** [XereoNet/SpaceBukkit#49]
Well i can read / write a little bit english, but i want to have spacebukkit in German for non English speakers. I want to set up some moderator account for a friend of mine, and well without english he may break my server. I would translate everything into German, but there seems no feature for installing new language, and i don't know the files which should be translated.

**Comment by Antariano** [comment]
We're working on localisation, don't worry :)

**Comment by JamyDev** [comment]
Going through all pages now, adding localisation support ;P

**Comment by Antariano** [comment]
Localisation support is almost complete, wait for official announcement
