### ISSUE TITLE
Issue with 3rd server on SpaceBukkit Panel

### ISSUE THREAD

**Issue by ghost** [XereoNet/SpaceBukkit#50]
I added my 3rd server to the SpaceBukkit and heres what I get on the chat page.

"Warning (2): Invalid argument supplied for foreach() [APP/Controller/DashController.php, line 348]"

When I click the Warning (2) I get this.

"DashController::get_chat_new() - APP/Controller/DashController.php, line 348
ReflectionMethod::invokeArgs() - [internal], line ??
Controller::invokeAction() - CORE/Cake/Controller/Controller.php, line 473
Dispatcher::_invoke() - CORE/Cake/Routing/Dispatcher.php, line 107
Dispatcher::dispatch() - CORE/Cake/Routing/Dispatcher.php, line 89
[main] - APP/webroot/index.php, line 96"

I only get this with my 3rd server whatsoever. Both, the first and second works just fine.

**Comment by davidcole1340** [comment]
I am having this problem with my server. Nothing works, but if you look in your server log, it says that the SpaceBukkit licence has expired.

**Comment by ghost** [comment]
My log says
"Your license is valid until 15/01/2012." Therefore, we are having a bit different situtations here.

**Comment by JamyDev** [comment]
Also for the 3rd server?

**Comment by ghost** [comment]
I use exactly the same license for all my 3 servers. (Roleplay, Vanilla and Megabuild)
Each of them gives me the same message.
"Your license is valid until 15/01/2012."

The message given at the first post whatsoever is the message I get only with the 3rd server, which happens to be my Megabuild server.

**Comment by JamyDev** [comment]
I'll check it out ..

**Comment by davidcole1340** [comment]
You know why I keep getting license expired?

**Comment by JamyDev** [comment]
@cheese5505 please use the latest version and key you got in your mail.
@ibab this means there was a connection issue. It seems that you've got a bad connection to your 3rd server... Which times out our chat checker.
