### ISSUE TITLE
[1.04]Plugins? Nope!

### ISSUE THREAD

**Issue by Lolmewn** [XereoNet/SpaceBukkit#54]
23:07:02 [SEVERE] Exception in thread "Thread-184"
23:07:02 [SEVERE] java.lang.NoClassDefFoundError: Could not initialize class a.a.a.e
23:07:02 [SEVERE]       at a.a.a.b.<init>(File:41)
23:07:02 [SEVERE]       at a.a.c.a(File:41)
23:07:02 [SEVERE]       at a.a.c.a(File:51)
23:07:02 [SEVERE]       at me.neatmonster.spacebukkit.a.a.a(File:278)
23:07:02 [SEVERE]       at me.neatmonster.spacebukkit.c.c.a(File:113)
23:07:02 [SEVERE]       at me.neatmonster.spacebukkit.c.c.a(File:45)
23:07:02 [SEVERE]       at me.neatmonster.spacebukkit.b.c.run(File:57)

**Comment by JamyDev** [comment]
repost https://github.com/NeatMonster/SpaceBukkit/issues/39

**Comment by Lolmewn** [comment]
Hey, I just closed that one!
