### ISSUE TITLE
New world gives error

### ISSUE THREAD

**Issue by Lolmewn** [XereoNet/SpaceBukkit#58]
Notice (8): Undefined variable: wrld [APP\Controller\TworldsController.php, line 568]
Code Context
TWorldsController::addWorld() - APP\Controller\TworldsController.php, line 568
ReflectionMethod::invokeArgs() - [internal], line ??
Controller::invokeAction() - CORE\Cake\Controller\Controller.php, line 473
Dispatcher::_invoke() - CORE\Cake\Routing\Dispatcher.php, line 107
Dispatcher::dispatch() - CORE\Cake\Routing\Dispatcher.php, line 89
[main] - APP\webroot\index.php, line 96

**Comment by JamyDev** [comment]
Can't reproduce the error; please disable all non-bukkit-approved plugins..

**Comment by Lolmewn** [comment]
but you saw it happen :(
