### ISSUE TITLE
Lampp, Internal error

### ISSUE THREAD

**Issue by ghost** [XereoNet/SpaceBukkit#59]
In the installation page, step with mysql, after entering all nevesary data and clicking next an "Internal error" appears.
Using Ubuntu Server, Lampp is configured to use existing mysql (all other things that rely on it are OK, including phpmyadmin)
Mysql is located on port 3336
I can provide additional info, just not sure what to post

**Comment by NeatMonster** [comment]
See http://spacebukkit.xereo.net/forum/index.php?topic=39.0, maybe it can help you with your issue.

**Comment by ghost** [comment]
Read it.. and it seems from the guy's replies that he just forgot to copy some web-related files... And I've copied everything..
Maybe you can tell me the place where to look for the errors cause? A log of some kind?

**Comment by JamyDev** [comment]
Please manyally change the port in ./app/Config/database.php to 3336 if that's your port ...
Normally mysql runs on 3306.

**Comment by ghost** [comment]
I did... and its the same... going to install 1.05 asap, but issue is not closed i think...

**Comment by JamyDev** [comment]
Any further info? Because it's quite difficult to go about from a 500 error..

**Comment by ghost** [comment]
Well some magic happened...I changed perms on a lampp folder to 755 (-R) and then it said "unable to write to /tmp"
Then I changed perms to 777 on htdocs from SB and it worked... So the error didnt manifest itself with 1.5
Can you tell me where to look for more detailed log when smth like error 500 happens? Thank you

**Comment by JamyDev** [comment]
A 500 shouldn't happen if you follow the instructions correct ;)
The video clearly said to chmod those folders ...

**Comment by ghost** [comment]
Well I did chmod them , anyway if i hadnt chmodded them they'd never run cuz they were copied from a windows machine... so idk what was the problem anyway :P

**Comment by DanzeeDan** [comment]
I just did something realllllllly stupid. In xamp you have a folder at /lampp/htdocs

Now normally, I would do "sudo sh install.sh" in lampp/htdocs/space but
Instead :( I did it in /lampp/htdocs and now xampp is screwed up and giving me an Internal Error 500.

Check at www.tribusclub.com 

Can anyone help!?
