### ISSUE TITLE
Issues with getting to the installation part

### ISSUE THREAD

**Issue by ghost** [XereoNet/SpaceBukkit#6]
Extracted the beta2.zip to the webserver. app/configuration.php is chmodded to 777, but the error still occurs.

Warning: require(../configuration.php): failed to open stream: No such file or directory in /var/www/html/SpaceBukkit/app/Config/bootstrap.php on line 3 Fatal error: require(): Failed opening required '../configuration.php' (include_path='.:/usr/share/pear:/usr/share/php') in /var/www/html/SpaceBukkit/app/Config/bootstrap.php on line 3

**Comment by Antariano** [comment]
Check if mod_rewrite is enabled on your Apache. We'll fix this crash occouring before the Environment check in v1.02

**Comment by ghost** [comment]
My httpd.conf has "LoadModule rewrite_module modules/mod_rewrite.so"

**Comment by Antariano** [comment]
Can I have the address to your webserver?

**Comment by ghost** [comment]
http://www.nextgenminecraft.net/SpaceBukkit/

**Comment by Antariano** [comment]
Allright, next version should fix it. It will be out tomorrow

**Comment by ghost** [comment]
Waiting forward to that then.
