### ISSUE TITLE
Exception when loading the Plugin tab

### ISSUE THREAD

**Issue by Grinch** [XereoNet/SpaceBukkit#64]
I get this when loading the Plugin tab. :(

03:35:18 [SEVERE] Exception in thread "Thread-233"
03:35:18 [SEVERE] java.lang.NullPointerException
03:35:18 [SEVERE]       at me.neatmonster.spacebukkit.web.Executor.getPluginInformations(Executor.java:587)
03:35:18 [SEVERE]       at me.neatmonster.spacebukkit.web.Interpretator.checkMethod(Interpretator.java:113)
03:35:18 [SEVERE]       at me.neatmonster.spacebukkit.web.Interpretator.interpret(Interpretator.java:45)
03:35:18 [SEVERE]       at me.neatmonster.spacebukkit.listeners.Listener.run(Listener.java:57)

**Comment by NeatMonster** [comment]
http://dl.dropbox.com/u/34835222/SpaceBukkit/latest.zip

**Comment by Grinch** [comment]
05:36:12 [SEVERE] Exception in thread "Thread-126"
05:36:12 [SEVERE] java.lang.NullPointerException
05:36:12 [SEVERE]       at me.neatmonster.spacebukkit.web.Executor.getPluginInformations(Executor.java:591)
05:36:12 [SEVERE]       at me.neatmonster.spacebukkit.web.Interpretator.checkMethod(Interpretator.java:113)
05:36:12 [SEVERE]       at me.neatmonster.spacebukkit.web.Interpretator.interpret(Interpretator.java:45)
05:36:12 [SEVERE]       at me.neatmonster.spacebukkit.listeners.Listener.run(Listener.java:57)

**Comment by NeatMonster** [comment]
http://dl.dropbox.com/u/34835222/SpaceBukkit/latest.zip again.
