### ISSUE TITLE
Java usage doesn't accurately display true usage

### ISSUE THREAD

**Issue by Grinch** [XereoNet/SpaceBukkit#66]
I am uncertain if Java usage means CPU or RAM usage but I give my server 1024 -> 4098mb of RAM and it usually says its around 70% ish on Java Usage.

My CPU usually never goes above 30% either.

**Comment by NeatMonster** [comment]
RAM usage.

Code used:
Runtime.getRuntime().totalMemory() - Runtime.getRuntime().freeMemory();

**Comment by NeatMonster** [comment]
http://dl.dropbox.com/u/34835222/SpaceBukkit/latest.zip

Edit: Updated again at 15:10 (GMT+1). This is the best I can do ATM.
