### ISSUE TITLE
Can not connect my main server.

### ISSUE THREAD

**Issue by CountVonCraft** [XereoNet/SpaceBukkit#67]
When i try and link my main server up to SpaceBukkit, i get this error in the console 

http://pastie.org/3085511

When trying to access the dashboard ect, it tells me maybe the server is offline (it is not)

Works fine on my creative server with less then 8 plugins.

This happens running 1.04 with 50+ plugins.

**Comment by NeatMonster** [comment]
Please update with http://dl.dropbox.com/u/34835222/SpaceBukkit/latest.zip and paste here the debug informations outputted in the console.
