### ISSUE TITLE
BukGet gives long list with 'Category'

### ISSUE THREAD

**Issue by Lolmewn** [XereoNet/SpaceBukkit#68]
Screenshot! 
http://dl.dropbox.com/u/7365249/ScreenShot004.jpg

**Comment by Antariano** [comment]
Thanks, I am having the same issue. Im on it

**Comment by JamyDev** [comment]
@Antariano This seems an issue on Bukget's part :/
http://bukget.org/api/categories

EDIT: Reported: https://github.com/SteveMcGrath/bukget/issues/49
EDIT²: Fixed :)
