### ISSUE TITLE
Scheduler not working - Freezing

### ISSUE THREAD

**Issue by ghost** [XereoNet/SpaceBukkit#69]
Hello. I have around 2 schedulers on my SpaceBukkit, which are the save world and say a message.
Whenever I try to remove one of these, the browser just keeps loading and loading infinitely and whenever I close the browser and try to access SpaceBukkit again, I can't. I need to restart the whole server to get it back functioning.

**Comment by JamyDev** [comment]
Fixed in 1.05 + Duplicate
