### ISSUE TITLE
Pannel freezes up when more then one user is loged in.

### ISSUE THREAD

**Issue by CountVonCraft** [XereoNet/SpaceBukkit#7]
If two or more users are loged in the whole pannel freezes up and will not load anything. Takes like an hour to unfreeze aswell, happens everytime, on both beta1 and beta2. Running linux CentOS.

**Comment by Antariano** [comment]
Are the said users on the same account?

**Comment by JamyDev** [comment]
Updated explanation in this issue: https://github.com/NeatMonster/SpaceBukkit/issues/8
