### ISSUE TITLE
SpaceBukkit won't install 1.05

### ISSUE THREAD

**Issue by TH3L0N3W0LF** [XereoNet/SpaceBukkit#73]
I tried to do a clean install of spaceBukkit and got this nasty error:
http://thw-lonewolf.net/P20111231000328.png

Running on Ubuntu Server 11.10 with a case sensitive filesystem.
This is a clean install, with no modification whatsoever. D:
Oddly enough, the app/Config/database.php file exists.

**Comment by TH3L0N3W0LF** [comment]
I'm sorry, I screwed up the link...
http://the-lonewolf.net/P20111231000328.png

**Comment by Alori** [comment]
As I installed v.1.05 a few hours ago i had the same problem.
Fixed it by adding "/install" to the web-address to access the install-script directly.
So my address looked like "http://localhost/105_web/install/".
I think a function to check the installation status is broken.
database.php will will not be generated with the script but seems to be in the zip-file.

**Comment by TH3L0N3W0LF** [comment]
Yep, that fixed it. ^^
Thanks Alori.

**Comment by JamyDev** [comment]
My bad, I forgot the initial inst.txt file. Updated http://dl.xereo.net/105_web.zip
