### ISSUE TITLE
World Type when creating new world needs to be case insensitive

### ISSUE THREAD

**Issue by Grinch** [XereoNet/SpaceBukkit#74]
Right now when creating a new world you have to type NORMAL, NETHER or THE_END. I think you should let it be case insensitive this way no matter how you type it, it will work.

**Comment by NeatMonster** [comment]
Maybe some kind of selector?

**Comment by Grinch** [comment]
That would work too. Skylands should also be removed from the options since Notch removed the Skylands code completely (to my knowledge). :)

**Comment by JamyDev** [comment]
Made it a selector ;)
