### ISSUE TITLE
Some plugins make BukGet crash

### ISSUE THREAD

**Issue by JamyDev** [XereoNet/SpaceBukkit#8]
http://pastie.org/3042358

for reference this is on Count's server

**Comment by NeatMonster** [comment]
xD

**Comment by Lolmewn** [comment]
I have the same, was just about to post this.

**Comment by Antariano** [comment]
Bukget was temporarily down for mainteneance. We'll include a check to see if it is online or not, so no crash occours.

**Comment by Antariano** [comment]
Cancel that, it was us failing the requests. We're reworking the bukget system

**Comment by Antariano** [comment]
https://github.com/NeatMonster/SpaceBukkit/issues/25

Duplicate issue
