### ISSUE TITLE
Players With Colour in their Names

### ISSUE THREAD

**Issue by Wundark** [XereoNet/SpaceBukkit#81]
If a player has colour in their name; by using a Plugin. EG. Essestials. It will cause the 'Players' page, to generate a blank page.

If a button is clicked whilst on a blank user it will cause a Thread exception and will stop SpaceBukkit completely.

**Comment by NeatMonster** [comment]
Any stacktrace?

**Comment by Wundark** [comment]
No, Its just that it shows a blank player.

When you click on something like "OP" it will just come up with a null pointer.

**Comment by NeatMonster** [comment]
Please paste the stacktracke even if it's unrelated to this issue. I'll investigate on this issue as soon as I get home.

**Comment by Wundark** [comment]
14:18:21 [SEVERE] Exception in thread "Thread-24"
14:18:21 [SEVERE] java.lang.NullPointerException
14:18:21 [SEVERE]       at org.bukkit.craftbukkit.CraftServer.getPlayerExact(CraftServer.java:246)
14:18:21 [SEVERE]       at org.bukkit.craftbukkit.CraftServer.getOfflinePlayer(CraftServer.java:819)
14:18:21 [SEVERE]       at org.bukkit.Bukkit.getOfflinePlayer(Bukkit.java:243)
14:18:21 [SEVERE]       at me.neatmonster.spacebukkit.web.Executor.opPlayer(Executor.java:893)
14:18:21 [SEVERE]       at me.neatmonster.spacebukkit.web.Interpretator.checkMethod(Interpretator.java:115)
14:18:21 [SEVERE]       at me.neatmonster.spacebukkit.web.Interpretator.interpret(Interpretator.java:17)
14:18:21 [SEVERE]       at me.neatmonster.spacebukkit.listeners.Listener.run(Listener.java:57)

**Comment by NeatMonster** [comment]
@Wundark This issue is solved in the Open Beta 1.0 version, wait for the Open Beta to released, this ticket will automatically be closed by the commit I made.
