### ISSUE TITLE
SpaceBukkitRTK is installed, but cannot be reached

### ISSUE THREAD

**Issue by davidcole1340** [XereoNet/SpaceBukkit#83]
SpaceBukkitRTK is installed, but when I start/reload the server, it says:

00:51:15 [SEVERE] ----------------------------------------------------------
00:51:15 [SEVERE] | SpaceBukkitRTK cannot be reached, please make sure you |
00:51:15 [SEVERE] | have RemoteToolkit installed, SpaceBukkitRTK placed in |
00:51:15 [SEVERE] | /toolkit/modules. Otherwise report this issue on our   |
00:51:15 [SEVERE] | issues tracker (http://bit.ly/spacebukkitissues).      |
00:51:15 [SEVERE] ----------------------------------------------------------

I have looked, `spacebukkit_module.jar` is there.

**Comment by drdanick** [comment]
Can you tell me what the output of the console command ".modules" is?

**Comment by davidcole1340** [comment]
```Currently loaded Toolkit modules:
  SpaceBukkitRTK [E]

```
```

**Comment by davidcole1340** [comment]
@drdanick

**Comment by davidcole1340** [comment]
@NeatMonster @JamyDev @Antariano ?

**Comment by fernferret** [comment]
@cheese5505 Github is not a live support fourm. All the devs were notified when yoru issue was created, therefore you don't have to keep making new messages trying to ping people.

**Comment by NeatMonster** [comment]
Do you see "Loading SpaceBukkit.jar (Licensed)...done." when starting the server?

(@FernFerret Thanks!)

**Comment by davidcole1340** [comment]
@NeatMonster No.

**Comment by NeatMonster** [comment]
@cheese5505 So the module isn't loaded. Please make sure spacebukkitrtk-dev-SNAPSHOT.jar in the /toolkit/modules folder and also make sure you are running RemoteToolkit.

**Comment by davidcole1340** [comment]
Weird.... Another restart of RemoteToolkit and it fixed it.
