### ISSUE TITLE
Current server properties aren't loaded

### ISSUE THREAD

**Issue by tobi1449** [XereoNet/SpaceBukkit#86]
When you go to the server properties tab, the current property values (like world seed, port, ...) aren't loaded and when you change and save it there, the empty values are saved.

**Comment by Antariano** [comment]
@Jamy did you change any of the code?

**Comment by JamyDev** [comment]
Loading code didn't change, ...
Op 15 jan. 2012 22:32 schreef "Luca Rager" <
reply@reply.github.com>
het volgende:

**Comment by tobi1449** [comment]
As far as I can remember it didn't work for me on the previous versions too. It may be a permissions problem but since writing just works fine (unfortunately >.<) it's unlikely.

**Comment by mrosun** [comment]
I have used the username Jamy on a number of gaming accounts and other
random websites but how my email got into this conversation, I have no idea.

On Monday, January 16, 2012, tobi1449 <
reply@reply.github.com>
wrote:

**Comment by Antariano** [comment]
I'm very sorry, Jamy, I forgot to put Dev at the end of your name! lol

**Comment by Antariano** [comment]
@tobi1449 what OS are you using?

**Comment by mrosun** [comment]
Oh no, I am meaning that I'm not the same Jamy as JamyDev, the Jamy you
know.

I never wrote any code, nor have any idea what you guys are talking about,
nor know what SpaceBukkit is.  I just don't know why this is sending to my
email, which is mihairosu@gmail.com.  I don't really mind that I'm getting
them honestly, but I just wanted to let you guys know in case there is a
more serious problem on your end.

All the best!

On Tuesday, January 17, 2012, Luca Rager <
reply@reply.github.com>
wrote:

**Comment by tobi1449** [comment]
I have the latest debian (v6.0.3)

**Comment by JamyDev** [comment]
Fixed, was a firefox only issue
