### ISSUE TITLE
Player page not working

### ISSUE THREAD

**Issue by davidcole1340** [XereoNet/SpaceBukkit#87]
Any idea why the player page isn't working? The image doesn't show up, It says that everyone is op (Not true), and it doesn't display their name and gamemode. Image: http://www.imgbomb.com/i/d15/3nhdo.png

**Comment by Antariano** [comment]
hm... are you using any plugin that gives colors or prefixes to a player?

**Comment by davidcole1340** [comment]
:/ Yup. Essentials' /nick command.

**Comment by Antariano** [comment]
Ok, then we have the issue. We're working on compatibility with those plugins already :)

**Comment by davidcole1340** [comment]
Cool :) Estimated version?
