### ISSUE TITLE
Error 500 - Internal server error on plugin remove

### ISSUE THREAD

**Issue by tobi1449** [XereoNet/SpaceBukkit#88]
Dunno if this is related to #82 but I get an error 500 when I try to remove a plugin. However I can't find any exception in any log, just an premature end of scripting headers in apache's error.log

**Comment by NeatMonster** [comment]
If there is no exception, it sounds like a panel related issue. @Antariano @JamyDev

**Comment by JamyDev** [comment]
Are you using the latest panel/plugin? 1.06 is the latest version ;)

**Comment by tobi1449** [comment]
Yes I am using the latest version, was the first thing I checked ;)

**Comment by Antariano** [comment]
Closed, will be reopened for 1.1 if error persists
