### ISSUE TITLE
Installing plugins via bukget doesn't work

### ISSUE THREAD

**Issue by tobi1449** [XereoNet/SpaceBukkit#89]
Spacebukkit tells me it has installed the plugin and I should reload/restart the server in order to see it but when I look into our servers plugin folder there's no new jar file (and therefore I can't see it in the list of plugins). Is there any way to see if it's a permission issue?

**Comment by NeatMonster** [comment]
@tobi1449 Any stacktrace? Can I also have more informations (plugin's name, etc)?

**Comment by tobi1449** [comment]
Happened with just all plugins I tested so far (latest one was FUN/openinv)and no stacktrace (just as I said, spacebukkit showed it's all ok and I would just need to reload/restart)

**Comment by NeatMonster** [comment]
@tobi1449 OK, thanks.

**Comment by NeatMonster** [comment]
@Antariano

**Comment by Antariano** [comment]
Seems to be an OS related issue, we're on it

**Comment by JamyDev** [comment]
Guessing this is fixed?

**Comment by tobi1449** [comment]
looks like

**Comment by Antariano** [comment]
Closed
