### ISSUE TITLE
Speed up the plugins page

### ISSUE THREAD

**Issue by Antariano** [XereoNet/SpaceBukkit#93]

**Comment by Antariano** [comment]
Allright, Neatmonster did some improvements, I did some improvements.
Now I need to think of ways to speed up the initial load.
Maybe a cache, or maybe structuring the calls differently.

**Comment by Antariano** [comment]
@NeatMonster, is it possible to split up getPluginInformations into seprate smaller calls to speed things up?

**Comment by NeatMonster** [comment]
@Antariano Sure, I think the best is the separate plugins standard informations and BukGet informations.

**Comment by Antariano** [comment]
Closed for now since we did indeed speed it up a bit. 
We'll improve it again for open beta, rest assured
